name: workflow-permissions

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

jobs:
  set-permissions:
    name: Set workflow permissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
